name: Deploy Cloud Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

      # - name: Setup GCP Service Account
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     project_id: ${{env.PROJECT}}
      #     service_account_key: ${{ secrets.GCP_SA }}
      #     export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: test-lab
          runtime: node10
          project_id: pub-sub
          credentials: ${{secrets.GCP_SA_KEY}}
          # entry_point: functions.ILoveMkdev

      # - name: make the url aunthenticated
      #   run: |
      #     gcloud functions add-iam-policy-binding ILoveMkdev --member="allUsers" --role="roles/cloudfunctions.invoker"

      - name: test the url
        run: |
          echo "${{ steps.deploy.outputs.url }}"
          curl "${{ steps.deploy.outputs.url }}"
